<?php

namespace miltapasBundle\Repository;

/**
 * tapaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tapaRepository extends \Doctrine\ORM\EntityRepository
{
}
